AWSTemplateFormatVersion: '2010-09-09'
Description: EC2 instance with auto start/stop during business hours

Parameters:
  InstanceType:
    Type: String
    Default: t4g.nano
    Description: EC2 instance type
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instance.

Resources:
  DevEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      ImageId: ami-08f3e969e66cd963a
      KeyName: !Ref KeyName

  DevSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH access
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0

Outputs:
  InstanceId:
    Description: "Instance ID of the newly created EC2 instance"
    Value: !Ref DevEC2Instance